server:
  port: 8082

spring:
  application:
    name: FILE-SERVICE  # MUST match Gateway route uri: lb://FILE-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/file_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

storage:
  upload-dir: D:/GoogleDriveClone/storage

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true